### ISSUE TITLE
Token Required

### ISSUE THREAD

**Issue by pschlieker** [jwdempsey/SongCast#2]
Hello, the skill is a great idea :+1: Unfortunately Spotify changed their API a month ago now requiring Tokens for each request. If I try to make a request i get the error
` {
  "error": {
    "status": 401,
    "message": "No token provided"
  }
}`
I was wondering if you already found the time to fix this. Cheers

**Comment by jwdempsey** [comment]
I am going to be making some changes to the skill over the next few weeks (including using the new Spotify Connect API) and hopefully I can resolve this issue. I appreciate you taking the time to try this out.

**Comment by jwdempsey** [comment]
This should be resolved now.
